INSERT INTO emprestimo.cliente (id, anotacao, nome) VALUES (1,'sem anotações','Neil Gaiman');



INSERT INTO emprestimo.cliente (`nome`,`anotacao`,`status`) VALUES ("Sparks","soups","LIBERADO"),("Burks","soups","LIBERADO"),("Trujillo","seafood","LIBERADO"),("Doyle","cereals","LIBERADO"),("Daniel","pasta","LIBERADO"),("Le","sandwiches","LIBERADO"),("Chase","salads","LIBERADO"),("Macdonald","soups","LIBERADO"),("Slater","cereals","LIBERADO"),("Blackwell","sandwiches","LIBERADO");
INSERT INTO emprestimo.cliente (`nome`,`anotacao`,`status`) VALUES ("Morgan","stews","BLOQUEADO"),("Camacho","desserts","BLOQUEADO"),("Dorsey","sandwiches","BLOQUEADO"),("Carroll","cereals","BLOQUEADO"),("Fuller","soups","BLOQUEADO"),("Anthony","pasta","BLOQUEADO"),("White","cereals","BLOQUEADO"),("Bush","seafood","BLOQUEADO"),("Strickland","sandwiches","BLOQUEADO"),("Howard","cereals","BLOQUEADO");
INSERT INTO emprestimo.cliente (`nome`,`anotacao`,`status`) VALUES ("Santiago","sandwiches","LIBERADO"),("Boone","pasta","LIBERADO"),("Carpenter","sandwiches","LIBERADO"),("Hunter","soups","LIBERADO"),("Rogers","cereals","LIBERADO"),("Bowers","noodles","LIBERADO"),("Wyatt","desserts","LIBERADO"),("Gallegos","soups","LIBERADO"),("Brock","pasta","LIBERADO"),("Kim","pasta","LIBERADO");
INSERT INTO emprestimo.cliente (`nome`,`anotacao`,`status`) VALUES ("Pena","cereals","BLOQUEADO"),("Rivas","cereals","BLOQUEADO"),("Chambers","salads","BLOQUEADO"),("Mcneil","salads","BLOQUEADO"),("Velez","pasta","BLOQUEADO"),("Herring","sandwiches","BLOQUEADO"),("Lambert","stews","BLOQUEADO"),("Gould","soups","BLOQUEADO"),("Walsh","pasta","BLOQUEADO"),("Copeland","salads","BLOQUEADO");
INSERT INTO emprestimo.cliente (`nome`,`anotacao`,`status`) VALUES ("Todd","noodles","LIBERADO"),("Jefferson","pasta","LIBERADO"),("Dean","cereals","LIBERADO"),("Mcbride","seafood","LIBERADO"),("Frazier","desserts","LIBERADO"),("Ruiz","pies","LIBERADO"),("Logan","soups","LIBERADO"),("Mann","soups","LIBERADO"),("Beck","desserts","LIBERADO"),("Harding","cereals","LIBERADO");
INSERT INTO emprestimo.cliente (`nome`,`anotacao`,`status`) VALUES ("Faulkner","noodles","BLOQUEADO"),("Kidd","pasta","BLOQUEADO"),("Mcdonald","seafood","BLOQUEADO"),("Chang","stews","BLOQUEADO"),("Vasquez","noodles","BLOQUEADO"),("Rogers","noodles","BLOQUEADO"),("Crosby","desserts","BLOQUEADO"),("Mckee","noodles","BLOQUEADO"),("Ramirez","noodles","BLOQUEADO"),("Logan","pasta","BLOQUEADO");
INSERT INTO emprestimo.cliente (`nome`,`anotacao`,`status`) VALUES ("Joyner","salads","LIBERADO"),("Owen","seafood","LIBERADO"),("Macias","seafood","LIBERADO"),("Chan","soups","LIBERADO"),("Blake","pasta","LIBERADO"),("English","desserts","LIBERADO"),("Moran","sandwiches","LIBERADO"),("Abbott","pasta","LIBERADO"),("Figueroa","seafood","LIBERADO"),("Hicks","stews","LIBERADO");
INSERT INTO emprestimo.cliente (`nome`,`anotacao`,`status`) VALUES ("Mcpherson","pasta","BLOQUEADO"),("Adams","seafood","BLOQUEADO"),("Castillo","salads","BLOQUEADO"),("Pollard","stews","BLOQUEADO"),("Downs","stews","BLOQUEADO"),("Lambert","desserts","BLOQUEADO"),("Mccarthy","desserts","BLOQUEADO"),("Sweeney","noodles","BLOQUEADO"),("Stevenson","pasta","BLOQUEADO"),("Dunlap","soups","BLOQUEADO");
INSERT INTO emprestimo.cliente (`nome`,`anotacao`,`status`) VALUES ("Mccoy","cereals","LIBERADO"),("Barber","pies","LIBERADO"),("Love","desserts","LIBERADO"),("Rich","sandwiches","LIBERADO"),("Gallagher","stews","LIBERADO"),("Barry","stews","LIBERADO"),("Moon","noodles","LIBERADO"),("Compton","pies","LIBERADO"),("Patton","cereals","LIBERADO"),("Maddox","pies","LIBERADO");
INSERT INTO emprestimo.cliente (`nome`,`anotacao`,`status`) VALUES ("Hopkins","stews","BLOQUEADO"),("Odom","stews","BLOQUEADO"),("Galloway","cereals","BLOQUEADO"),("Brooks","pasta","BLOQUEADO"),("Neal","sandwiches","BLOQUEADO"),("Wiggins","seafood","BLOQUEADO"),("Sexton","soups","BLOQUEADO"),("Stout","soups","BLOQUEADO"),("Bauer","pasta","BLOQUEADO"),("Pugh","pies","BLOQUEADO");
